### ISSUE TITLE
error when start

### ISSUE THREAD

**Issue by mtbig999** [trustin/gleamstream#1]
v.1.2.1
16:15:01.214 [main] ERROR Unexpected exception from main:
java.io.FileNotFoundException: C:\Users\(USERNAME)\AppData\Roaming\gleamstream\unique_id (지정된 경로를 찾을 수 없습니다)
-> make dir manual

**Comment by mtbig999** [comment]
gleamstream v.1.2.1
nvidia-exp v.3.2.2.49
C:\Users\(USERNAME)\Desktop\gleamstream-1.2.1\bin>gleamstream.bat -connect 127.0.0.1
16:18:26.450 [main] INFO  Loading native libraries
16:18:29.161 [main] INFO  OS classifier: windows-x86_64
16:18:29.487 [main] INFO  Loading preferences
16:18:29.487 [main] INFO  Loading the unique ID of the machine
16:18:29.497 [main] INFO  Loading the default gamepad mappings
16:18:30.222 [tasks] INFO  Launching application
16:18:30.264 [tasks] INFO  Loaded key pair from disk
16:18:31.383 [tasks] ERROR Unexpected exception from tasks:
java.net.ConnectException: Failed to connect to /127.0.0.1:47984
        at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConn
ection.java:143)
        at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection
.java:112)
        at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(Str
eamAllocation.java:184)
        at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnect
ion(StreamAllocation.java:126)
        at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAl
location.java:95)
        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:
281)
        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.j
ava:224)
        at com.squareup.okhttp.Call.getResponse(Call.java:286)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.jav
a:243)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:20
5)
        at com.squareup.okhttp.Call.execute(Call.java:80)
        at com.limelight.nvstream.http.NvHTTP.openHttpConnection(NvHTTP.java:298
)
        at com.limelight.nvstream.http.NvHTTP.openHttpConnectionToString(NvHTTP.
java:328)
        at com.limelight.nvstream.http.NvHTTP.getServerInfo(NvHTTP.java:213)
        at com.limelight.nvstream.NvConnection.startApp(NvConnection.java:138)
        at com.limelight.nvstream.NvConnection.establishConnection(NvConnection.
java:342)
        at com.limelight.nvstream.NvConnection.start(NvConnection.java:390)
        at kr.motd.gleamstream.Main.lambda$connect$1(Main.java:170)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

-> it occur when stop gamestream
-> need message for help

**Comment by mtbig999** [comment]
C:\Users\(USERNAME)\Desktop\gleamstream-1.2.1\bin>gleamstream.bat -connect 127.0.0.1

17:03:13.089 [main] INFO  Loading native libraries
17:03:13.780 [main] INFO  OS classifier: windows-x86_64
17:03:14.097 [main] INFO  Loading preferences
17:03:14.097 [main] INFO  Loading the unique ID of the machine
17:03:14.105 [main] INFO  Loading the default gamepad mappings
17:03:14.509 [tasks] INFO  Launching application
17:03:14.553 [tasks] INFO  Loaded key pair from disk
17:03:14.702 [tasks] INFO  Server major version: 7
17:03:14.745 [tasks] INFO  App ID: 999999
17:03:14.746 [tasks] INFO  Launching a new session ..
17:03:16.035 [tasks] ERROR Unexpected exception from tasks:
com.limelight.nvstream.http.GfeHttpResponseException: GFE error: Cannot launch t
he game as it's been started locally. (Error code: 526)
        at com.limelight.nvstream.http.NvHTTP.verifyResponseStatus(NvHTTP.java:1
98)
        at com.limelight.nvstream.http.NvHTTP.getXmlString(NvHTTP.java:168)
        at com.limelight.nvstream.http.NvHTTP.getXmlString(NvHTTP.java:188)
        at com.limelight.nvstream.http.NvHTTP.launchApp(NvHTTP.java:643)
        at com.limelight.nvstream.NvConnection.launchNotRunningApp(NvConnection.
java:291)
        at com.limelight.nvstream.NvConnection.startApp(NvConnection.java:262)
        at com.limelight.nvstream.NvConnection.establishConnection(NvConnection.
java:342)
        at com.limelight.nvstream.NvConnection.start(NvConnection.java:390)
        at kr.motd.gleamstream.Main.lambda$connect$1(Main.java:170)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

-> finding solution...
